---
services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: $PROJECT_NAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $PROJECT_NAME
    ports:
      - $DATABASE_PORT:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: $PROJECT_NAME
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    environment:
      PROJECT_NAME: $PROJECT_NAME
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: $PROJECT_NAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME: $PROJECT_NAME
    ports:
      - $APP_PORT:8000
    depends_on:
      - db

volumes:
  postgres:
