# Generated by Django 5.1.4 on 2025-01-18 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name; has to be unique.', max_length=50, unique=True)),
                ('description', models.TextField(help_text='What is this for?')),
                ('is_enabled', models.BooleanField(default=False, help_text='Is this enabled?')),
                ('created_at', models.TimeField(auto_now_add=True, help_text='Date and time of creation.')),
                ('updated_at', models.TimeField(auto_now=True, help_text='Date and time of update.')),
                ('author', models.ForeignKey(editable=False, help_text='Creator.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
