name: Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-24.04
    container: python:3.12
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt

      - name: Run Tests
        run: |
          python src/manage.py test
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: example
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
